name: Centre Stage HK
favicon: null
layout_spectrum: 0.32649
typography_spectrum: 0.9062173566780984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f79323'
    - '#fefefe'
    - '#4f4f4f'
    - '#808185'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
