name: Centre Stage HK
favicon: null
layout_spectrum: 0.71495
typography_spectrum: 0.63361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f79323'
    - '#fefefe'
    - '#4f4f4f'
    - '#808185'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
