name: Centre Stage HK
favicon: null
layout_spectrum: 0.4728727228939533
typography_spectrum: 0.9062173566780984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6931e'
    - '#ffffff'
    - '#000000'
    - '#959595'
    - '#643a0f'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
